import type { Metadata } from "next";
import {
  Rubik as RubikFont,
  Open_Sans,
  Dancing_Script,
} from "next/font/google";
import "./globals.css";

const rubik = RubikFont({
  subsets: ["latin"],
  variable: "--font-rubik",
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={rubik.className}>
      <body>{children}</body>
    </html>
  );
}
